// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  File = 1,
  Note = 2,
  Date = 3,
  MetaKey = 4,
  Set = 5,
  Rep = 6,
  Failure = 7,
  Movement = 8,
  Load = 9
