// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./highlight.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "hOVQPOOOOQO'#Cf'#CfQVQPOOOOQO-E6d-E6d",
  stateData: "q~O]OS~OQPORPOSPOTPOUPOVPOWPOXPO~O",
  goto: "bZPPPPPPPPPP[QQORRQ",
  nodeNames: "⚠ File Note Date MetaKey Set Rep Failure Movement Load",
  maxTerm: 13,
  propSources: [highlighting],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "&f~RaX^!Wpq!Wst!{z{#d!Q![#{!b!c%i!c!}&Q#R#S&Q#T#o&Q#y#z!W$f$g!W#BY#BZ!W$IS$I_!W$I|$JO!W$JT$JU!W$KV$KW!W&FU&FV!W~!]Y]~X^!Wpq!W#y#z!W$f$g!W#BY#BZ!W$IS$I_!W$I|$JO!W$JT$JU!W$KV$KW!W&FU&FV!W~#QSS~OY!{Z;'S!{;'S;=`#^<%lO!{~#aP;=`<%l!{~#iSQ~OY#dZ;'S#d;'S;=`#u<%lO#d~#xP;=`<%l#d~$OaX^%Tpq%T!Q![#{!h!i%Y!t!u%_!u!v%d#Y#Z%Y#f#g%_#g#h%d#y#z%T$f$g%T#BY#BZ%T$IS$I_%T$I|$JO%T$JT$JU%T$KV$KW%T&FU&FV%T~%YOX~~%_OV~~%dOU~~%iOT~~%nSR~OY%iZ;'S%i;'S;=`%z<%lO%i~%}P;=`<%l%i~&TS![!]&a!c!}&Q#R#S&Q#T#o&Q~&fOW~",
  tokenizers: [0],
  topRules: {"File":[0,1]},
  tokenPrec: 0
})
