// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!|OVQPOOOeQPO'#C^OmQPO'#C`OuQPO'#CbO!WQQO'#ChOOQO'#Ck'#CkQVQPOOOOQO,58x,58xOOQO,58z,58zOOQO'#Cl'#ClO!]QPO,58|O!pQPO,59SOOQO-E6i-E6iOOQO-E6j-E6jOOQO1G.n1G.n",
  stateData: "!x~OcOS~ORPOTQOVRO]SO~OdVOeVO~OdWOeWO~OWXOXXOYXOZXOeXO~O^ZO~ORUaTUaVUa]UaaUa~PuOd^Oe^O~O",
  goto: "raPPbPbPbPPPPPbPPflTTOUQUOR[UQYRR]Y",
  nodeNames: "⚠ File Note NoteValue Date DateValue Movement MovementName Load Rep Set Failure Meta MetaName MetaValue",
  maxTerm: 21,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "*j~RfXY!gYZ!rpq!gst!wz{$R{|$j!O!P%w!Q![%w!]!^!r!b!c'r!c!d(Z!d!e(q!e!y(Z!y!z(q!z!}(Z#R#S(Z#T#U(Z#U#V(q#V#k(Z#k#l(q#l#o(Z~~*e~!lQc~XY!gpq!g~!wOe~~!zVpq#a!O!P#a!Q![#a!a!b#a!c!}#a#R#S#a#T#o#a~#dWpq#a!O!P#a!Q![#a![!]#|!a!b#a!c!}#a#R#S#a#T#o#a~$RO]~~$WSR~OY$RZ;'S$R;'S;=`$d<%lO$R~$gP;=`<%l$RP$maX^%rpq%r{|$j!O!P$j!Q![$j!d!e$j!y!z$j#U#V$j#k#l$j#y#z%r$f$g%r#BY#BZ%r$IS$I_%r$I|$JO%r$JT$JU%r$KV$KW%r&FU&FV%rP%wOWP~%zgX^%rpq%r{|$j!O!P%w!Q![%w!d!e$j!h!i'c!t!u'h!u!v'm!y!z$j#U#V$j#Y#Z'c#f#g'h#g#h'm#k#l$j#y#z%r$f$g%r#BY#BZ%r$IS$I_%r$I|$JO%r$JT$JU%r$KV$KW%r&FU&FV%r~'hOZ~~'mOX~~'rOY~~'wST~OY'rZ;'S'r;'S;=`(T<%lO'r~(WP;=`<%l'rR(`S^Q![!](l!c!}(Z#R#S(Z#T#o(ZP(qOVPR(vi^QX^%rpq%r{|$j!O!P$j!Q![$j![!](l!c!d(Z!d!e(q!e!y(Z!y!z(q!z!}(Z#R#S(Z#T#U(Z#U#V(q#V#k(Z#k#l(q#l#o(Z#y#z%r$f$g%r#BY#BZ%r$IS$I_%r$I|$JO%r$JT$JU%r$KV$KW%r&FU&FV%r~*jOd~",
  tokenizers: [0, 1],
  topRules: {"File":[0,1]},
  tokenPrec: 0
})
