// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!|OVQPOOOhQPO'#C^OpQPO'#C`OxQPO'#CbO!ZQQO'#CiOOQO'#Cl'#ClQVQPOOOOQO,58x,58xOOQO,58z,58zOOQO'#Cm'#CmO!`QPO,58|O!vQPO,59TOOQO-E6j-E6jOOQO-E6k-E6kOOQO1G.o1G.o",
  stateData: "#O~OdOS~ORPOTQOVRO[RO^SO~OeVOfVO~OeWOfWO~OWXOXXOYXOZXOfXO~O_ZO~ORUaTUaVUa[Ua^UabUa~PxOe^Of^O~O",
  goto: "sbPPcPcPcPPPPPPcPPgmTTOUQUOR[UQYRR]Y",
  nodeNames: "⚠ File Note NoteValue Date DateValue Movement MovementName Load Rep Set Failure SuperSetMovementName Meta MetaName MetaValue",
  maxTerm: 22,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "._~RfXY!gYZ!rpq!gst!wz{$R{|$j!O!P)l!Q![)l!]!^!r!b!c+g!c!d,O!d!e,f!e!y,O!y!z,f!z!},O#R#S,O#T#U,O#U#V,f#V#k,O#k#l,f#l#o,O~~.Y~!lQd~XY!gpq!g~!wOf~~!zVpq#a!O!P#a!Q![#a!a!b#a!c!}#a#R#S#a#T#o#a~#dWpq#a!O!P#a!Q![#a![!]#|!a!b#a!c!}#a#R#S#a#T#o#a~$RO^~~$WSR~OY$RZ;'S$R;'S;=`$d<%lO$R~$gP;=`<%l$R~$mhX^&Xpq&X{|&^!O!P&^!Q![&^!c!d'f!d!e'z!e!y'f!y!z'z!z!}'f#R#S'f#T#U'f#U#V'z#V#k'f#k#l'z#l#o'f#y#z&X$f$g&X#BY#BZ&X$IS$I_&X$I|$JO&X$JT$JU&X$KV$KW&X&FU&FV&XP&^OWPP&aaX^&Xpq&X{|&^!O!P&^!Q![&^!d!e&^!y!z&^#U#V&^#k#l&^#y#z&X$f$g&X#BY#BZ&X$IS$I_&X$I|$JO&X$JT$JU&X$KV$KW&X&FU&FV&X~'iS![!]'u!c!}'f#R#S'f#T#o'f~'zO[~~'}iX^&Xpq&X{|&^!O!P&^!Q![&^![!]'u!c!d'f!d!e'z!e!y'f!y!z'z!z!}'f#R#S'f#T#U'f#U#V'z#V#k'f#k#l'z#l#o'f#y#z&X$f$g&X#BY#BZ&X$IS$I_&X$I|$JO&X$JT$JU&X$KV$KW&X&FU&FV&X~)ogX^&Xpq&X{|&^!O!P)l!Q![)l!d!e&^!h!i+W!t!u+]!u!v+b!y!z&^#U#V&^#Y#Z+W#f#g+]#g#h+b#k#l&^#y#z&X$f$g&X#BY#BZ&X$IS$I_&X$I|$JO&X$JT$JU&X$KV$KW&X&FU&FV&X~+]OZ~~+bOX~~+gOY~~+lST~OY+gZ;'S+g;'S;=`+x<%lO+g~+{P;=`<%l+gR,TS_Q![!],a!c!},O#R#S,O#T#o,OP,fOVPR,ki_QX^&Xpq&X{|&^!O!P&^!Q![&^![!],a!c!d,O!d!e,f!e!y,O!y!z,f!z!},O#R#S,O#T#U,O#U#V,f#V#k,O#k#l,f#l#o,O#y#z&X$f$g&X#BY#BZ&X$IS$I_&X$I|$JO&X$JT$JU&X$KV$KW&X&FU&FV&X~._Oe~",
  tokenizers: [0, 1],
  topRules: {"File":[0,1]},
  tokenPrec: 0
})
