// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  File = 1,
  Note = 2,
  NoteValue = 3,
  Date = 4,
  DateValue = 5,
  Movement = 6,
  MovementName = 7,
  Load = 8,
  Rep = 9,
  Set = 10,
  Failure = 11,
  SuperSetMovementName = 12,
  Meta = 13,
  MetaName = 14,
  MetaValue = 15
